// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_SaveEventLocations","status":true,"description":"v1.06 Enable specified maps to memorize the locations of\nevents when leaving and loading them upon reentering map.","parameters":{}}
];
